version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - redis_network
    environment:
      redis_pwd: '${redis_pwd}'
    command: redis-server --save 20 1 --loglevel warning --requirepass $redis_pwd
networks:
  redis_network:
    driver: bridge