version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: demon_mongo_server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PWD}'

volumes:
  mongodb_data: